CREATE TABLE IF NOT EXISTS mi_fund_transfer_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_key VARCHAR(64) NOT NULL,
    active_slot TINYINT NULL DEFAULT 1,
    user_id VARCHAR(64) NOT NULL DEFAULT 'default',
    username VARCHAR(128) NOT NULL,
    status VARCHAR(48) NOT NULL,
    step VARCHAR(48) NOT NULL,
    status_message VARCHAR(500) NULL,
    coin VARCHAR(32) NOT NULL,
    network VARCHAR(32) NOT NULL,
    destination_masked VARCHAR(128) NOT NULL,
    requested_amount DECIMAL(24,8) NOT NULL,
    expected_fee DECIMAL(24,8) NOT NULL,
    withdraw_amount DECIMAL(24,8) NOT NULL,
    actual_fee DECIMAL(24,8) NULL,
    received_amount DECIMAL(24,8) NULL,
    binance_transfer_client_id VARCHAR(64) NOT NULL,
    binance_transfer_id VARCHAR(128) NULL,
    binance_rollback_client_id VARCHAR(64) NOT NULL,
    binance_rollback_id VARCHAR(128) NULL,
    binance_withdraw_order_id VARCHAR(64) NOT NULL,
    binance_withdraw_id VARCHAR(128) NULL,
    binance_tx_id VARCHAR(255) NULL,
    gate_deposit_id VARCHAR(128) NULL,
    gate_transfer_client_id VARCHAR(64) NOT NULL,
    gate_transfer_id VARCHAR(128) NULL,
    attention_required TINYINT(1) NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    detail JSON NULL,
    delayed_notified_at DATETIME NULL,
    attention_notified_at DATETIME NULL,
    last_checked_at DATETIME NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_fund_transfer_task_key (task_key),
    UNIQUE KEY uk_fund_transfer_active_slot (active_slot),
    UNIQUE KEY uk_fund_transfer_binance_client (binance_transfer_client_id),
    UNIQUE KEY uk_fund_transfer_binance_rollback_client (binance_rollback_client_id),
    UNIQUE KEY uk_fund_transfer_withdraw_order (binance_withdraw_order_id),
    UNIQUE KEY uk_fund_transfer_gate_client (gate_transfer_client_id),
    INDEX idx_fund_transfer_created (created_at),
    INDEX idx_fund_transfer_status (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
